<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_applyNow</name>
   <tag></tag>
   <elementGuidId>2a0e6293-b3d5-4eed-8b3f-4b78f7271dad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;contentConvention&quot;]/div[2]/div/div[2]/div[2]/div[2]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;contentConvention&quot;]/div[2]/div/div[2]/div[2]/div[2]/button[1]</value>
      <webElementGuid>c6ba35f1-8d8f-4b38-b6e9-f1e6522482ff</webElementGuid>
   </webElementProperties>
</WebElementEntity>
