<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_IDType</name>
   <tag></tag>
   <elementGuidId>71905a76-96cf-4ad6-96e2-607ed8fe406f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div/div[1]/div[3]/div/div/div/div[2]/div/div/div[4]/div[2]/div/div[2]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div[1]/div[3]/div/div/div/div[2]/div/div/div[4]/div[2]/div/div[2]/div/div/button</value>
      <webElementGuid>935db8a1-d703-4360-89f8-6c6c8a53ef69</webElementGuid>
   </webElementProperties>
</WebElementEntity>
