<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_personal</name>
   <tag></tag>
   <elementGuidId>80a06e55-6820-4b9d-b26d-0fc9be929e53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;header&quot;]/div/div[2]/div/nav/ul/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;header&quot;]/div/div[2]/div/nav/ul/li[1]/a</value>
      <webElementGuid>30363da4-1108-4575-9a18-3a9a924e2800</webElementGuid>
   </webElementProperties>
</WebElementEntity>
