<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Business2</name>
   <tag></tag>
   <elementGuidId>05e14479-15bf-4db6-99e6-0009ee4d5f25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mainNav&quot;]/div/div/div[2]/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mainNav&quot;]/div/div/div[2]/div/ul/li[2]/a</value>
      <webElementGuid>e62aa47b-1bec-4f12-a67d-69ecd4abc655</webElementGuid>
   </webElementProperties>
</WebElementEntity>
