<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_personal2</name>
   <tag></tag>
   <elementGuidId>966ae851-ff26-4538-ab35-f839f938c7ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mainNav&quot;]/div/div/div[2]/div/ul/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mainNav&quot;]/div/div/div[2]/div/ul/li[1]/a</value>
      <webElementGuid>2730d895-cc57-4f9d-a757-5e512887f86a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
