<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_IDType</name>
   <tag></tag>
   <elementGuidId>623a669c-5864-49e3-8970-0a8581f5e7c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div/div[1]/div[3]/div/div/div/div[2]/div/div/div[4]/div[2]/div/div[2]/div/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div[1]/div[3]/div/div/div/div[2]/div/div/div[4]/div[2]/div/div[2]/div/div/ul/li[2]/a</value>
      <webElementGuid>1190174a-a38e-419d-8df4-85674179496b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
